# Entorno de desarrollo
#
# solo es necesario una vez:
#  * make -f Makefile.dev dev-setup
#
# luego se pueden ejecutar las pruebas:
#  * make -f Makefile.dev test

.PHONY: dev-setup dev-shell py-develop test tox

dev-setup:
	docker build -t facho .

dev-shell:
	docker run --rm -ti -v "$(PWD):/app" -w /app --name facho-cli facho bash

test:
	docker run -t -v $(PWD):/app -w /app facho sh -c 'cd /app; python3.7 setup.py test'

tox:
	docker run -it -v $(PWD)/:/app -w /app facho tox
