# Entorno de desarrollo
#
# solo es necesario una vez:
#  * make -f Makefile.dev dev-setup
#
# luego se pueden ejecutar las pruebas:
#  * make -f Makefile.dev test

.PHONY: dev-setup
dev-setup:
	docker build -t facho .

.PHONY: test
test:
	docker run -t -v $(PWD):/app -w /app facho sh -c 'cd /app; python3.7 setup.py test'

.PHONY: tox
tox:
	docker run -it -v $(PWD)/:/app -w /app facho tox
